spring:
  cloud:
    function:
      definition: consumer;producer
    stream:
      bindings:
        producer-out-0:
          destination: first-topic
        consumer-in-0:
          destination: first-topic
      poller:
        fixed-delay: 5000
      kafka:
        bindings:
          consumer-in-0:
            consumer:
              start-offset: earliest
debug: on
